import "./globals.css";
import StoreProvider from "./StoreProvider";
export const metadata = {
  title: "Login Form",
  description: "Generated by muhammad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-600">
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
